version: '2'

services:

  tensorflow:
    container_name: tensorflow
    image: sofwerx/android_tensorflow_object_detection
    build:
      context: .
      dockerfile: Dockerfile.base
#      cache_from: sofwerx/android_tensorflow_object_detection:latest
    volumes:
      - "./outputs:/outputs"

